# Generated by Django 3.2.13 on 2022-10-18 15:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/'),
        ),
    ]
